// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201508150423_DataModel_Event_add_isdelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201508150423_DataModel_Event_add_isdelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201508151054337_201508150423_DataModel_Event_add_isdelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
