// <auto-generated />
namespace CustomAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomAuthentication_User_Delete_Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomAuthentication_User_Delete_Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201508081238225_CustomAuthentication_User_Delete_Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
